%YAML 1.2
---
# dispathcer configs

"dispatcher":
    # backtrack: parameter for backtrack dispatcher, will pass to BackTrackDispatcher
    "thread_workers": null           # number of workers for subscriber, no include the main loop

    # time step in seconds for backtest
    "start_dt": 2017-03-04 12:00:00  # backtrack start time
    "end_dt": 2017-03-07 12:00:00    # backtrack end time
    # trace_process_time, if set to true, the event process time is added to now
    "trace_process_time": true
    # limit current time, will not newer than datetime.now()
    "limit_time": true
