%YAML 1.2
---
# enabled backtrack exts
"enabled_backtrack_exts":
    - "backtrack_test"

# enabled live track exts
"enabled_live_exts":
    - "live_test"

# configure extensions configures for backtrack
"exts":
    "finchan.exts.scheduler":
        # time event frequency, unit is second
        "frequency": 1
    "finchan.exts.period_call":
        # process time in second
        "process_time": 1
