%YAML 1.2
---
# The main configure file

"version": 1
# "run_mode": support live/backtrack
"run_mode": "live"

"work_dir": "~/.finchan"

# parameters for backtrack ext_manage, will pass to ExtManager
"ext_manager":
    # extensions' path
    "ext_path":
        - "~/"
