%YAML 1.2
---
# backtrack exts' configs

"enabled_backtrack_exts":
    - "backtrack_test"

# configure extensions configures for backtrack
"backtrack_exts":
    "finchan.exts.scheduler":
    "finchan.exts.period_call":
        # process time in second
        "process_time": 3
