%YAML 1.2
---
# live track exts' configs

"enabled_live_exts":
    - "live_test"

# configure extensions configures for backtrack
"live_track_exts":
    "finchan.exts.timer_source":
        # time event frequency, unit is second
        "frequency": 1
    "finchan.exts.timer_callback":
        # process time in second
        "process_time": 1
